global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'portfolio_rebalancer'
    static_configs:
      - targets: ['127.0.0.11:8081', '127.0.0.11:8082', '127.0.0.11:8083']
    metrics_path: /health # I will need to develop a dedicated /metrics endpoint... until then this is will be just chilling here
    scrape_timeout: 10s
    honor_labels: true
    scheme: http