server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: 'job'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: 'container'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_config_hash']
        target_label: 'compose_config_hash'
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            operation: operation
            portfolio_id: portfolio_id
            correlation_id: correlation_id
            duration: duration_seconds
            error_code: error_code
            error_category: error_category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          operation:
          error_category:
      - output:
          source: message

  # Analytics service specific log collection
  - job_name: analytics-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics-service
          __path__: /var/log/portfolio-rebalancer/analytics*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            operation: operation
            portfolio_id: portfolio_id
            correlation_id: correlation_id
            duration: duration_seconds
            error_code: error_code
            error_category: error_category
            service: service
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          operation:
          service:
          error_category:
      - output:
          source: message

  # Kubernetes pod logs for analytics
  - job_name: kubernetes-pods-analytics
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - portfolio-rebalancer
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: analytics|analytics-worker
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_label_component]
        target_label: component
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            operation: operation
            portfolio_id: portfolio_id
            correlation_id: correlation_id
            duration: duration_seconds
            error_code: error_code
            error_category: error_category
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          operation:
          component:
          error_category:
      - output:
          source: message