apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
data:
  # Data Configuration
  TICKERS: "SPY,QQQ,VTI,VXUS,BND"
  STORAGE_TYPE: "parquet"
  STORAGE_PATH: "/app/data"
  BACKFILL_DAYS: "252"
  
  # Optimization Configuration
  USER_AGE: "35"
  RISK_FREE_RATE: "0.02"
  LOOKBACK_DAYS: "252"
  MIN_WEIGHT: "0.0"
  MAX_WEIGHT: "0.4"
  SAFE_PORTFOLIO_BONDS: "0.8"
  
  # Executor Configuration
  REBALANCE_THRESHOLD: "0.05"
  ORDER_TYPE: "market"
  BROKER_TYPE: "alpaca"
  
  # Broker Configuration (non-sensitive)
  ALPACA_BASE_URL: "https://paper-api.alpaca.markets"
  IB_HOST: "127.0.0.1"
  IB_PORT: "7497"
  IB_CLIENT_ID: "1"
  
  # Scheduler Configuration
  EXECUTION_TIME: "16:30"
  TIMEZONE: "America/New_York"
  RETRY_ATTEMPTS: "3"
  RETRY_DELAY: "300"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_FILE_PATH: "/app/logs/portfolio_rebalancer.log"
  
  # Security Configuration
  USE_ENCRYPTED_CREDENTIALS: "true"
  ENABLE_ENCRYPTION: "true"
  CREDENTIAL_STORAGE_PATH: "/app/.credentials"
  KEY_STORAGE_PATH: "/app/.keys"
  CREDENTIAL_ROTATION_DAYS: "90"
  ENABLE_SECURE_COMMUNICATION: "true"
  SSL_VERIFY: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
    component: analytics
data:
  # Analytics Service Configuration
  ANALYTICS_SERVICE_PORT: "8084"
  WEBSOCKET_PORT: "8085"
  PROMETHEUS_METRICS_PORT: "8086"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_URL: "redis://redis-service:6379/0"
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis-service:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/2"
  
  # WebSocket Configuration
  WEBSOCKET_HOST: "0.0.0.0"
  
  # Analytics Configuration
  ANALYTICS_CACHE_TTL: "3600"
  ANALYTICS_MAX_CONCURRENT_TASKS: "5"
  ANALYTICS_TASK_TIMEOUT: "1800"
  ANALYTICS_DEFAULT_BACKTEST_DAYS: "252"
  ANALYTICS_MAX_MONTE_CARLO_SIMULATIONS: "50000"
  
  # Database Configuration (non-sensitive)
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "portfolio_rebalancer"
  
  # Monitoring Configuration
  ENABLE_PROMETHEUS_METRICS: "true"
  METRICS_UPDATE_INTERVAL: "30"
  
  # Security Configuration
  ENABLE_ANALYTICS_AUTH: "true"
  ANALYTICS_CORS_ORIGINS: "*"
  ANALYTICS_MAX_REQUEST_SIZE: "10485760"  # 10MB
  
  # Performance Configuration
  ANALYTICS_WORKER_CONCURRENCY: "2"
  ANALYTICS_PREFETCH_MULTIPLIER: "4"
  ANALYTICS_TASK_SOFT_TIME_LIMIT: "1500"
  ANALYTICS_TASK_TIME_LIMIT: "1800"