apiVersion: v1
kind: Secret
metadata:
  name: broker-credentials
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded credentials
  # To encode: echo -n "your_api_key" | base64
  ALPACA_API_KEY: eW91cl9hbHBhY2FfYXBpX2tleQ==  # your_alpaca_api_key
  ALPACA_SECRET_KEY: eW91cl9hbHBhY2Ffc2VjcmV0X2tleQ==  # your_alpaca_secret_key
  
  # For other brokers, add additional credentials as needed
  # TD_CLIENT_ID: eW91cl90ZF9jbGllbnRfaWQ=
  # TD_REFRESH_TOKEN: eW91cl90ZF9yZWZyZXNoX3Rva2Vu