---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-fetcher-service
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
    component: fetcher
spec:
  selector:
    app: portfolio-rebalancer
    component: fetcher
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-optimizer-service
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
    component: optimizer
spec:
  selector:
    app: portfolio-rebalancer
    component: optimizer
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-executor-service
  namespace: portfolio-rebalancer
  labels:
    app: portfolio-rebalancer
    component: executor
spec:
  selector:
    app: portfolio-rebalancer
    component: executor
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP
  type: ClusterIP